### ISSUE TITLE
No way to set project name, it assumes a project name

### ISSUE THREAD

**Issue by neomatrix369** [wandb/client-java#3]
I had some success running the jar file as mentioned in https://github.com/wandb/client-java/issues/2 although couldn't find a way to set the project name. After it finishes the run, I noticed it picked up the name of the git repo which I currently stood as the name of the `wanb` project. 

A work-around for now would be great to have, @raubitsj mentions setting the project name as an environment variable.

I found this in the `wandb` help docs:

```
wandb init --project [NAME OF PROJECT TO USE]
```

Would this work for now?

**Comment by raubitsj** [comment]
This is how you set a project programmatically:
```
iff --git a/examples/java/java-sin/src/main/java/com/wandbj/sinfunc/Example.java b/examples/java/java-sin/src/main/java/com/wandbj/sinfunc/Example.java
index b192d9a..fc5940a 100644
--- a/examples/java/java-sin/src/main/java/com/wandbj/sinfunc/Example.java
+++ b/examples/java/java-sin/src/main/java/com/wandbj/sinfunc/Example.java
@@ -20,6 +20,7 @@ public class Example {
         // Using builder to create run object
         System.out.println("Creating wandb run object.");
         WandbRun run = new WandbRun.Builder()
+                .withProject("myproject")
                 .withConfig(config)
                 .build();
```

`wandb init` or setting an environment variable does not work currently.
